stoplightio/http-spec

package.json
src/oas2/transformers/__tests__/__snapshots__/responses.test.ts.snap
src/oas2/transformers/__tests__/responses.test.ts
src/oas2/transformers/responses.ts
tsconfig.build.json
yarn.lock

In the current implementation every example gets copied in every content — but they should not. In OAS2 the *key* of the example is the *mimeType* of the example itself, and they should go in their relative content.

Fix content examples for OAS2

---

src/oas3/transformers/__tests__/content.test.ts
src/oas3/transformers/content.ts

This is required to bring https://github.com/stoplightio/prism/issues/496 over the finish line

fix: check array includes only if style is defined

---

src/oas3/transformers/__tests__/__snapshots__/content.test.ts.snap
src/oas3/transformers/__tests__/content.test.ts
src/oas3/transformers/content.ts

Addresses https://github.com/stoplightio/studio/issues/80.
The question is - why did we decide to pick property `value` only? If it was intended, perhaps the issue reported in Studio is not an actual bug but a feature?

fix(content): include whole example

---

src/oas3/transformers/__tests__/__snapshots__/content.test.ts.snap
src/oas3/transformers/content.ts

- Examples should have a key, value, summary, and description property as described in https://github.com/stoplightio/types/blob/master/src/graph.ts#L27
- Related to https://github.com/stoplightio/studio-internal/pull/706
- OAS3 examples have a value property: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#example-object
- https://swagger.io/docs/specification/adding-examples/

fix: revert example value change

---

package.json
src/oas2/__tests__/accessors.test.ts
src/oas2/accessors.ts
src/oas2/index.ts
src/oas2/operation.ts
yarn.lock

For some reason that I can't really remember OAS2 produces consumes default to `*/*`, even if the document has nothing in it.
On the other hand, in OAS3 this default mechanism is not a thing. This discrepancy is giving us troubles in Prism since we need to write special code to accomplish the same thing.
Unfortunately we lost the history because of the new repository — but if anybody recalls the reason, please speak up. Otherwise, this will uniform the behaviour between oas2 and 3.

Do not create default produces

---

package.json
src/oas3/__tests__/__snapshots__/operation.test.ts.snap
src/oas3/__tests__/operation.test.ts
src/oas3/operation.ts
src/oas3/transformers/callbacks.ts
yarn.lock

Introduces a capability for reading callbacks from OASv3 specs. Needs https://github.com/stoplightio/types/pull/54 to be merged first (types).
The motivation behind extending the IHttpOperation interface: callbacks in OASv3 spec are wrapped in an object with callback name as property and operation as value. SL's way of representing such objects is to convert it to an array and add a property inside with the key name (see operations array, examples array, etc.). This change is compatible with that approach.
**Master PR**: https://github.com/stoplightio/prism/pull/716
**Related issue**: https://github.com/stoplightio/prism/issues/331
**The spec**: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#callbackObject
**Callback example**: …

feat: oas3 callbacks support

---

src/oas2/transformers/__tests__/params.test.ts
src/oas2/transformers/params.ts
src/oas3/transformers/__tests__/content.test.ts
src/oas3/transformers/content.ts

Add support for unsupported schema properties: `readOnly, writeOnly, xml and externalDocs`

Preserve readOnly, writeOnly, xml and externalDocs in schemas

---

src/oas3/guards.ts

Addresses: https://github.com/stoplightio/studio-internal/issues/1448#event-2895785126
Newly added response header wasn't treated as oas3 header when building virtual node
Changes:
- include `schema` when checking if object is Parameter (Header)

fix: include schema in parameter check

---

src/oas2/__tests__/__snapshots__/operation.test.ts.snap
src/oas2/__tests__/accessors.test.ts
src/oas2/accessors.ts

According to [OAS 2 spec](https://swagger.io/docs/specification/2-0/authentication):
> Global security can be overridden in individual operations to use a different authentication type, different OAuth 2 scopes, or no authentication at all.
This PR adds ability to override oauth2 definition scopes with an operation scopes and it should fix https://github.com/stoplightio/platform/issues/1599

fix: override definition scopes with operation scopes

---

src/oas/types.ts

Graphite references that enum.
Needed to make the graphite->platform switch.
https://github.com/stoplightio/graphite/blob/master/src/plugins/http/oas2.ts#L2
https://github.com/stoplightio/graphite/blob/master/src/plugins/http/oas3.ts#L2

fix: enum OasVersion cannot be const

---

src/oas2/index.ts
src/oas3/index.ts
src/oas3/transformers/request.ts

Required by https://github.com/stoplightio/graphite/pull/348
Exports oas3 parameter translation function needed to compare path parameters between source map and virtual nodes

chore: export translate parameter

---

src/oas3/__tests__/__snapshots__/operation.test.ts.snap
src/oas3/__tests__/operation.test.ts
src/oas3/__tests__/service.test.ts
src/oas3/service.ts
src/oas3/transformers/servers.ts

Related Issue: https://github.com/stoplightio/http-spec/issues/53
* Include servers and server variables when transforming an OpenAPI v3 spec to an IHttpService

feat: add server variable support

---

package.json
src/postman/__tests__/operation.test.ts
src/postman/operation.ts
src/postman/transformers/__tests__/params.test.ts
src/postman/transformers/__tests__/request.test.ts
src/postman/transformers/__tests__/securitySchemes.spec.ts
src/postman/transformers/params.ts
src/postman/transformers/response.ts
src/postman/transformers/securityScheme.ts
yarn.lock

Postman-collection types are now fixed (https://github.com/DefinitelyTyped/DefinitelyTyped/pull/42582) so we no longer need explicit casts and other workarounds to get postman-collection transform work.
This PR removes unnecessary code.

Postman Collection: Types fixes

---

src/postman/transformers/request.ts

Fixes case when `url.path` is not defined.
There is also a pull request to `DefinitelyTyped` which fixes the types: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/42833

Postman Collection: handles case when url.path is not defined

---

src/__tests__/merge.test.ts
src/merge.ts
src/postman/__tests__/operation.test.ts
src/postman/operation.ts

Fixes #74.
Introduces the initial capability of merging together two `IHttpOperation`'s. 
The feature is required because:
- Postman stores as separate items making it possible to e.g. define few 200 responses
- Postman may store few items (operations) defining the same endpoint
There are few things missing to call it full-blown solution:
- security merging - might be slightly required by PC, we could consider adding it
- callbacks - not required for PC
Note: The only-client of this feature currently is Postman Collection transformations

Postman Collection: Merging IHttpOperations

---

src/postman/transformers/__tests__/response.test.ts
src/postman/transformers/response.ts

PC typings state that `cookie.expires` is an `Date|undefined`. However an integer timestamp is also an accepted value:
- implementation: https://github.com/postmanlabs/postman-collection/blob/develop/lib/collection/cookie.js#L142
- example: https://github.com/postmanlabs/postman-collection/blob/develop/examples/collection-v2.json#L75
This PR prepares `http-spec` to handle such case.

Postman Collection cookie.expires fix

---

src/__tests__/merge.test.ts
src/merge.ts

Case insensitive comparison of header/mediaType/server.url when merging.

fix: handling letter cases when merging http ops

---

src/merge.ts
src/postman/operation.ts

This PR improves the typings of the merger. Now the merger function is typed with array type instead of the item type. That makes it possible to pass some more complex array types, like NonEmptyArray.
There is still an open case: https://github.com/stoplightio/http-spec/pull/82/files#diff-047f6c9db2a76331a04cf84790e05f5bR85. Should we prevent creating operations with empty responses on `http-spec` level? Currently, we allow such operations which result e.g. in prism being unable to mock such request. WDYT?

chore: improved typings for IHttpOperation merger

---

jest.config.js
package.json
src/oas2/__tests__/accessors.test.ts
src/oas2/__tests__/guards.test.ts
src/oas2/__tests__/operation.test.ts
src/oas2/accessors.ts
src/oas2/guards.ts
src/oas2/operation.ts
src/oas2/service.ts
src/oas2/transformers/__tests__/__snapshots__/request.test.ts.snap
src/oas2/transformers/__tests__/request.test.ts
src/oas2/transformers/request.ts
src/oas2/transformers/securities.ts
src/oas3/accessors.ts
src/oas3/service.ts
src/oas3/transformers/content.ts
src/postman/__tests__/operation.test.ts
src/postman/operation.ts
src/postman/transformers/params.ts
src/postman/transformers/response.ts
src/utils.ts
yarn.lock

* Upgrade all the dependencies
* TypeScript 3.8 pointed out some typing errors that were not reported by TypeScript 3.7, I've fixed these
* I've put a link to the DefinitelyTyped PR that will fix two ts ignore directives we have at the moment
* Removed the casting for Postman Collections

chore: upgrade dependencies

---

tsconfig.json

Http-Spec has been upgraded to sl-scripts 8 which does not produce commonjs exports. This PR restores the output to what it was before

fix: commonjs

---

package.json
src/postman/__tests__/operation.test.ts
src/postman/transformers/__tests__/params.test.ts
src/postman/transformers/__tests__/request.test.ts
src/postman/transformers/__tests__/response.test.ts
src/postman/transformers/params.ts
yarn.lock

Makes all parameters extracted from Postman Collection required:
1) path params
2) query params
3) headers
4) object properties in generated schemas for body payload
In order to achieve 4) I replaced [to-json-schema](https://github.com/ruzicka/to-json-schema) with [json-schema-generator](https://github.com/krg7880/json-schema-generator). I'm not happy about both libs but the latter at least produces good results. The bad thing about the lib is that it looks not to be maintained. But other libs had bigger problems: not able to turn `required` on, no control over `additionalProperties` or producing JSONSchema3.
I'd say that if we want to proceed with "learning" we need some strong library and `json-schema-generator` looks like a candidate which can serve some foundation for this (uses AST …

Postman Collection: Required parameters

---

.eslintrc.js
src/oas/__tests__/__snapshots__/operation.test.ts.snap
src/oas/__tests__/accessors.test.ts
src/oas/__tests__/operation.test.ts
src/oas/accessors.ts
src/oas2/guards.ts
src/oas2/operation.ts
src/oas2/transformers/__tests__/responses.test.ts
src/oas2/transformers/responses.ts
src/oas3/accessors.ts
src/oas3/operation.ts
src/oas3/transformers/__tests__/responses.test.ts
src/oas3/transformers/responses.ts
src/oas3/transformers/servers.ts
src/utils.ts

Fixes https://github.com/stoplightio/platform-internal/issues/3039
Fixes https://github.com/stoplightio/platform-internal/issues/2946
Due to new bundle strategy, incoming documents might have local $refs in them. We need to handle this case.
After these changes (compare to screenshots in 3039 linked above):
Note nice params and responses in righthand preview:
Same thing, nice params and responses:

fix: local references in params and responses

---

src/oas3/transformers/__tests__/content.test.ts
src/oas3/transformers/content.ts

long story short - http-spec should never throw an error, otherwise X task in Y project won't succeed and ultimately no preview panel will be rendered for a given document or node.
This is occurring quite often: https://sentry.io/organizations/stoplightio/issues/1673691344/?project=1549141&query=is%3Aunresolved+properties&statsPeriod=14d

fix(oas): openapi-schema-to-json-schema may throw

---

package.json
yarn.lock

Upgrades openapi converter to 3.0.1 that can handle circular references when used with `cloneSchema: true` (ALWAYS in our case)

fix: upgrade openapi converter

---

src/oas2/transformers/__tests__/getExamplesFromSchema.test.ts
src/oas2/transformers/getExamplesFromSchema.ts

- fixes https://github.com/stoplightio/platform-internal/issues/3501

fix: handle invalid schema data

---

src/oas/__tests__/__snapshots__/operation.test.ts.snap
src/oas2/__tests__/service.test.ts
src/oas2/accessors.ts
src/oas2/service.ts
src/oas3/__tests__/accessors.test.ts
src/oas3/__tests__/service.test.ts
src/oas3/accessors.ts
src/oas3/service.ts
src/oas3/transformers/__tests__/securities.test.ts

This PR will make sure that only the scopes that are defined in the operation security scope will be effectively copied in the final operation.
I am open to better alternatives to implement the filter.

fix: filter out foreign scopes

---

src/oas2/guards.ts
src/oas2/transformers/securities.ts
src/oas3/guards.ts
src/oas3/transformers/securities.ts

We should really stop using `DeepPartial<Xyz>` pattern - this is incorrect for most of the time.
We usually don't validate the provided input in any way before operating on it.
Moreover, using `pickBy` is just not quite great IMHO when it comes to typings, same as `get` is.
`Object.assign` was removed as it clobbered typing and was tad inconsistent with the how oas2 was implemented.

fix(oas): security flows transformation is incorrect

---

src/oas3/__tests__/operation.test.ts

The test was first introduced in #129, but empty `properties` are now preserved thanks to #130.
#130 didn't have all the changes from master, therefore the tests passed (the failing test didn't even exist on that branch)

test(oas3): update expected output

---

src/oas2/guards.ts
src/oas2/transformers/__tests__/servers.test.ts
src/oas2/transformers/servers.ts

Fixes https://github.com/stoplightio/elements/issues/904
Validates server schemes against invalid characters (i.e. whitespaces or leading numbers) that would throw if passed to `URI`.

fix: server scheme validation

---

README.md
package.json
src/oas/operation.ts
src/oas3/__tests__/operation.test.ts
src/oas3/__tests__/service.test.ts
src/oas3/operation.ts
src/oas3/service.ts
src/oas3/transformers/__tests__/responses.test.ts
src/oas3/transformers/securities.ts
yarn.lock

Addresses stoplightio/platform-internal#5776 
Needs https://github.com/stoplightio/types/pull/79
I didn't add tests for the following
> ensure that spaceDelimited and pipeDelimited are allowed on object type (rc0 Extended Functionality)
This is rather out of scope for `http-spec`. I'd say it's more of a Studio work, to make sure it's capable of generating a good example, i.e. http://spec.openapis.org/oas/v3.1.0#style-examples.
`http-spec` does not care what kind of type is given, it only cares about the style, and this is preserved.
> ensure that style, explode and allowReserved are allowed on multipart/form-data (rc0 Extended Functionality)
Reasoning: we don't seem to have such a need. This is how `IMediaTypeContent` looks like
```ts
export interface IHttpContent {
schema?: JSONSchema4 | …
```

feat(oas3): support all we need for now except schema

---

src/oas/__tests__/__snapshots__/operation.test.ts.snap
src/oas3/__tests__/operation.test.ts
src/oas3/guards.ts
src/oas3/transformers/request.ts

Addresses https://github.com/stoplightio/platform-internal/issues/5189
This PR adds support for references in the `requestBody` of operation object with corresponding tests. Also it fixes some snapshots where this feature was dropped intentionally.
According to [OAS3 Specification](http://spec.openapis.org/oas/v3.0.0#fixed-fields-7) operation object's `requestBody` can be a [Reference Object](http://spec.openapis.org/oas/v3.0.0#referenceObject).

feat(oas3): support requestBody references

---

src/oas/__tests__/__snapshots__/operation.test.ts.snap
src/oas/transformers/schema/__tests__/schema.spec.ts
src/oas/transformers/schema/index.ts
src/oas/transformers/schema/keywords/format.ts
src/oas3/__tests__/operation.test.ts

For https://github.com/stoplightio/platform-internal/pull/6083
List of changes:
- numeric `format` keywords are preserved
- we convert `additionalItems` - just in case
-  typings were tweaked a bit to indicate JSON Schema Draft 4 & Draft 6 are generally accepted.

feat(oas): minor adjustments to OAS Schema Object converter

---

src/oas/accessors.ts

Fixes stoplightio/platform-internal#7214

fix: ignore parameters without `name` or `in`

---

src/oas3/__tests__/operation.test.ts
src/oas3/transformers/request.ts

Fixes #154
Related to https://github.com/stoplightio/platform-internal/issues/6720 
2 questions:
- should I remove `example` parameter? I don't want to break stuff, but on the other hand it's not present in the IHttpParam interface at all. 🤷 
- do we have a good idea for the name of the key? `default`? `single`? Leave it blank? 🤔

fix: add parameter example to examples list

---

src/oas3/transformers/__tests__/responses.test.ts
src/oas3/transformers/responses.ts

Fixes the issue when a [header is set as $ref](https://spec.openapis.org/oas/v3.1.0#response-object)
```
headers: {
'X-Page': {
$ref: '#/components/headers/xPage',
},
},
```
In this case, we need to dereference the header object first and then assemble response object.

fix: dereferencing response headers objects before response assembling

---

package.json
yarn.lock

Hello !
What is inside this PR ?
I bumped `json-schema` and `postman-collection` because the oldest versions had security issues
- `json-schema` has fixed a prototype pollution in `v0.4.0` 
- `postman-collection` `v4.1.0` does not rely anymore on `sanitize-html@1` that had arbitrary code execution
Thanks anyway for the great job !

chore(dependencies): bump json-schema and postman-collection

---

package.json
src/oas/__tests__/__snapshots__/operation.test.ts.snap
src/oas/__tests__/fixtures/oas2-kitchen-sink.json
src/oas/__tests__/fixtures/oas3-kitchen-sink.json
src/oas/accessors.ts
src/oas2/__tests__/__snapshots__/operation.test.ts.snap
src/oas2/__tests__/operation.test.ts
src/oas2/operation.ts
src/oas3/__tests__/__snapshots__/operation.test.ts.snap
src/oas3/__tests__/operation.test.ts
src/oas3/operation.ts
yarn.lock

Addresses: https://github.com/stoplightio/platform-internal/issues/7772
~Requires: https://github.com/stoplightio/types/pull/97~
Transforming operation `x-extensions` properties to `HttpOperation` `extensions` property.

feat: http operation extensions

---

src/oas3/__tests__/accessors.test.ts
src/oas3/accessors.ts

For stoplightio/platform-internal#9530
It makes sure security is created for each scope. I've removed mapping to keys and then looking in `flattenPairs` in `getSecurities` function for it to work. Why was this done in the first place, I don't know. Maybe there is some use case I'm not aware of? 
All tests are passing tho 🤷‍♂️

fix: create security item for each scope

---

src/oas2/__tests__/operation.test.ts
src/oas2/transformers/__tests__/__snapshots__/request.test.ts.snap
src/oas2/transformers/__tests__/params.test.ts
src/oas2/transformers/__tests__/request.test.ts
src/oas2/transformers/params.ts
src/oas3/transformers/__tests__/content.test.ts

I spotted this accidentally.
It's not a huge issue as these ids wouldn't be consumed either way, but it's still good to address it to avoid any confusion in the future.
I also removed the remaining `jest.mock`

fix(oas2): redundant ids

---

src/oas/transformers/schema/__tests__/schema.spec.ts
src/oas/transformers/schema/keywords/number.ts

🤦‍♂️ 
Prior to the change - <img width="301" alt="image" src="https://user-images.githubusercontent.com/9273484/164450087-7ef64926-bbc3-40c7-a93b-677c269ba1df.png">
Stumbled upon this while working on #10914 when I was looking at how we handle exclusiveMinimum/exclusiveMaximum in http-spec vs json-schema-tree

fix(oas): false exclusive{Minimum,Maximum} not translated correctly

---

src/oas/transformers/schema/__tests__/schema.spec.ts
src/oas/transformers/schema/index.ts

Fixes https://github.com/stoplightio/platform-internal/issues/11303
It's not a new issue since this is how the old code used to work, but previously we didn't use `translateSchemaObject` in a few cases (which was an actual issue I fixed in 5.x), so perhaps that's where that increased error rate comes from.
Overall not a huge deal, but still good to get it addressed now that we use http-spec in even more spots.

fix(oas): translateSchemaObject does not handle circular references

---

src/oas/__tests__/__snapshots__/operation.test.ts.snap
src/oas/__tests__/fixtures/oas3-kitchen-sink.json
src/oas3/transformers/__tests__/__snapshots__/content.test.ts.snap
src/oas3/transformers/__tests__/content.test.ts
src/oas3/transformers/__tests__/responses.test.ts
src/oas3/transformers/content.ts
src/oas3/transformers/examples.ts

Stumbled upon this one thanks to https://github.com/stoplightio/types/pull/108
Weird we haven't had `externalValue` anywhere in our fixtures, but I suppose it's not particularly common.
FWIW this one is also not a new bug, it's been there since always? That's how it looked like in 4.3.1 https://github.com/stoplightio/http-spec/blob/v4.3.1/src/oas3/transformers/content.ts#L169

fix(oas3): support externalValue in example objects

---

package.json
src/oas/service.ts
src/oas2/__tests__/service.test.ts
src/oas3/__tests__/service.test.ts
yarn.lock

Transforms the 'x-internal' property in the oas document to internal.
Related to a change that was requested for this pr https://github.com/stoplightio/platform-internal/pull/12208

feat: set internal property on http services

---

src/oas/__tests__/operation.test.ts
src/oas/resolver.ts

discovered by https://github.com/stoplightio/prism/issues/2090
Prism runs `bundleTarget` on operations.
Would be cool to implement `bundleOas{2,3}Operation` same as we do with [bundleOas2Service](https://github.com/stoplightio/http-spec/blob/master/src/oas2/service.ts#L35) and [bundleOas3Service](https://github.com/stoplightio/http-spec/blob/master/src/oas3/service.ts#L26)

fix(oas): add setter so $refs can be set

---

src/oas/__tests__/__snapshots__/operation.test.ts.snap
src/oas/transformers/schema/__tests__/schema.spec.ts
src/oas/transformers/schema/keywords/format.ts
src/oas3/__tests__/operation.test.ts
src/oas3/transformers/__tests__/__snapshots__/responses.test.ts.snap

A default value is being provided for minimum and maximum when not found in the original schema. While this is intended behavior, there are times when we want to remove these values from the schema when transforming into different types. 
To help with this, we added an x-stoplight object to track which key/values are set explicitly in the original schema.  
Created an array of property names to track which values are in the schema prior to making changes. 
Ran existing test to validate that they failed, and then updated to pass.
I used yalc to pull into platform-internal to see that the new key value pair is available for use. 
No new tests were added since this case was covered with existing tests.

fix: indicate whether the min/max value were provided in the original schema

---

src/oas/transformers/schema/__tests__/schema.spec.ts
src/oas/transformers/schema/keywords/number.ts

As part of supporting OAS 3.1 exporter, I noticed that exclusiveMinimum and exclusiveMaximum values were not being preserved. Since we handle changing this behavior with the drafts, it makes sense to preserve these values during the http spec process
Reminder: 
OAS3 - exclusiveMin / Max are booleans
OAS3.1 - exclusiveMin / Max are integers
#https://github.com/stoplightio/platform-internal/issues/15265
check to see if value is a number and do not delete from schema if it is
added test to capture exclusiveMin / Max with integer value
yarn test locally
yalc'd into platform internal and confirmed that all exporter tests (oas2, 3, 3.1) are passsing

fix(oas): change how exclusiveMin & Max are handled

---

src/oas2/transformers/__tests__/servers.test.ts
src/oas2/transformers/servers.ts

when a host specifies 443 and the scheme is http or ws, the port is dropped by the `URL` type. this should make that happen. added tests to cover this scenario

fix(oas2): fix http/ws hosts on port 443

---

src/generators.ts
src/oas/__tests__/__snapshots__/operation.test.ts.snap
src/oas2/__tests__/__fixtures__/id/bundled.ts
src/oas2/transformers/__tests__/__snapshots__/params.test.ts.snap
src/oas2/transformers/params.ts
src/oas3/__tests__/__fixtures__/id/bundled.ts
src/oas3/__tests__/__fixtures__/id/legacy.ts
src/oas3/__tests__/__fixtures__/shared-components/bundled.ts
src/oas3/__tests__/__fixtures__/shared-components/legacy.ts
src/oas3/__tests__/bundle.test.ts
src/oas3/transformers/headers.ts
src/oas3/transformers/request.ts

[#15985](https://github.com/stoplightio/platform-internal/issues/15985)
- adds new `componentType` prop to http_header id generator
- this distinguishes a header defined in `parameters` and a header defined in `headers` that have the same key and ensures they have unique ids
- units tests added and updated
- yalc'd this into platform-internal and it fixes the issues seen in export when a parameter and header have the same key. Also didn't seem to break any of the other analyzer, studio, etc. tests.

fix: 15985 parameter and header with same key should have unique ids

---

src/oas2/transformers/__tests__/__snapshots__/request.test.ts.snap
src/oas2/transformers/__tests__/params.test.ts
src/oas2/transformers/__tests__/request.test.ts
src/oas2/transformers/params.ts

[#16280](https://github.com/stoplightio/platform-internal/issues/16280)
Make sure body params do not get mapped to form data consumes values and visa versa
- unit tests

fix: 16280 match body and formdata params to their respective consumes

---

src/oas2/__tests__/__fixtures__/id/bundled.ts
src/oas2/service.ts

Even though they aren't used directly in the bundle itself (due to our handling of consumes/produces), we should include them so that SL Doc can correctly link cross-file references.

fix(oas2): include shared responses in bundled service

---

src/oas3/__tests__/bundle.test.ts
src/oas3/transformers/responses.ts

[#17558](https://github.com/stoplightio/platform-internal/issues/17558)
- do not drop operation responses if they have an external ref along their chain of refs
- unit test
- yalc'd into platform-internal and tested with refs.spec.ts

fix(oas): do not drop operation responses if they have eternal ref

---

src/oas/__tests__/__snapshots__/operation.test.ts.snap
src/oas/__tests__/fixtures/oas2-kitchen-sink.json
src/oas/__tests__/fixtures/oas3-kitchen-sink.json
src/oas2/__tests__/__snapshots__/operation.test.ts.snap
src/oas2/__tests__/accessors.test.ts
src/oas2/__tests__/operation.test.ts
src/oas2/accessors.ts

Optional support was missing for oas2 (swagger), but only at the operation level.

fix(oas2): operation optional security support

---

package.json
src/oas/__tests__/__snapshots__/operation.test.ts.snap
src/oas/transformers/schema/__tests__/schema.spec.ts
src/oas/transformers/schema/keywords/format.ts
yarn.lock

Currently, `MAX_INT_64` is set to `2 ** 63 - 1`, and `MIN_INT_64` is set to `0 - 2 ** 63` in `src/oas/transformers/schema/keywords/format.ts`. The TypeScript compiler evaluates these, respectively, to 9223372036854776000 and -9223372036854776000. 
These values are outside the range of int64 and result in bugs in clients such as Prism that use this library (e.g. https://github.com/stoplightio/prism/issues/1992). 
The reasoning behind this erroneous calculation is explained here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER. Essentially, we are overflowing the capacity of JavaScript's Number type, and beyond Number.MAX_SAFE_INTEGER + 1 (9007199254740992), the IEEE-754 floating-point format can no longer represent every consecutive …

Fix int64 overflow issue to due precision issues in Typescript with large numbers

---

src/__tests__/generators.test.ts
src/generators.ts
src/oas/__tests__/__snapshots__/operation.test.ts.snap
src/oas/__tests__/fixtures/oas3-kitchen-sink.json
src/oas/operation.ts
src/oas3/operation.ts
src/oas3/transformers/__tests__/callbacks.test.ts
src/oas3/transformers/callbacks.ts
src/types.ts

Addresses: https://github.com/stoplightio/platform-internal/issues/18498
Callback ids are currently being generated based on operation method and path. This may lead to duplicated ids in case where one operation has more than one callbacks defined.
Adds additional key property (callback name) when generating ids for callback nodes.
Tests updated

fix: callback operation ids

---

src/oas3/__tests__/accessors.test.ts
src/oas3/accessors.ts

The PR is required for displaying security scheme roles in elements: https://github.com/stoplightio/elements/issues/2491
The `scopes` value has been added to `extensions` as it's not part of the security scheme, so I didn't want to extend `HttpSecurityScheme`.
Tested locally in elements.

feat(oas3): return security scopes for types other than oauth2
