stoplightio/http-spec

- package.json
- yarn.lock
Closes #1 
I wanted to get rid of the 3 build files but there are file copies here and there required in the build process I can't take care right now
> fix: restore sl-scripts build

- tsconfig.build.json
> fix: commonjs module

- package.json
- src/oas3/transformers/__tests__/__snapshots__/content.test.ts.snap
- src/oas3/transformers/content.ts
- yarn.lock
Convert to JSON Schema the JSONish one that OAS3 provides.
> fix: nested properties

- package.json
- src/oas3/transformers/__tests__/content.test.ts
- yarn.lock
Fixes https://github.com/stoplightio/studio-internal/issues/1031
The actual fix will need to be provided in https://github.com/philsturgeon/openapi-schema-to-json-schema/
> fix: handle incorrect schemas gracefully

- src/oas/__tests__/service.test.ts
- src/oas2/__tests__/service.test.ts
- src/oas2/service.ts
- src/oas3/__tests__/service.test.ts
- src/oas3/service.ts
Fixes https://github.com/stoplightio/studio-internal/issues/1056
> fix: safer servers/schemes processing

- src/oas2/__tests__/accessors.test.ts
- src/oas2/accessors.ts
Potentially related to https://github.com/stoplightio/studio-internal/issues/998
> fix(oas2): handle malformed consumes/produces gracefully

- src/oas2/transformers/__tests__/servers.test.ts
- src/oas2/transformers/servers.ts
Related to https://github.com/stoplightio/studio-internal/issues/998
> fix(oas2): invalid operation servers are translated properly

- src/oas3/guards.ts
- src/oas3/transformers/__tests__/__snapshots__/content.test.ts.snap
- src/oas3/transformers/__tests__/content.test.ts
- src/oas3/transformers/__tests__/responses.test.ts
- src/oas3/transformers/content.ts
- src/oas3/transformers/responses.ts
Fixes https://github.com/stoplightio/studio-internal/issues/1053
> fix: handle nullish headers

- package.json
- yarn.lock
This PR is no really required but I messed up the previous publish process so we need something else to publish.
> fix: upgrade packages

- src/oas3/transformers/__tests__/__snapshots__/servers.test.ts.snap
- src/oas3/transformers/servers.ts
Fixes someone's lazy snapshot testing 🙄
> fix: server description

- src/oas3/__tests__/operation.test.ts
- src/oas3/guards.ts
- src/oas3/operation.ts
- src/oas3/transformers/__tests__/__snapshots__/servers.test.ts.snap
- src/oas3/transformers/__tests__/servers.test.ts
- src/oas3/transformers/servers.ts
Should help with https://github.com/stoplightio/studio-internal/issues/1212
> fix(oas3): filter out invalid servers and server variables

- src/oas/__tests__/accessors.test.ts
- src/oas/accessors.ts
- src/oas2/operation.ts
- src/oas3/__tests__/operation.test.ts
- src/oas3/operation.ts
Fixes https://github.com/stoplightio/studio-internal/issues/998
> fix(oas): normalize operation tags

- src/oas2/__tests__/service.test.ts
- src/oas2/service.ts
- src/oas3/__tests__/service.test.ts
- src/oas3/service.ts
Addresses https://github.com/stoplightio/studio-internal/issues/1346
> fix: handle invalid document securities gracefully

- src/oas2/transformers/__tests__/servers.test.ts
- src/oas2/transformers/servers.ts
Addresses https://github.com/stoplightio/studio-internal/issues/1363
> fix(oas2): handle invalid server host

- src/oas/__tests__/accessors.test.ts
- src/oas/accessors.ts
- src/oas2/__tests__/operation.test.ts
- src/oas2/operation.ts
- src/oas3/__tests__/operation.test.ts
- src/oas3/operation.ts
- src/oas3/transformers/request.ts
Fixes https://github.com/stoplightio/studio-internal/issues/1608
> fix: filter out null request parameters

- src/oas3/__tests__/service.test.ts
- src/oas3/transformers/securities.ts
Should fix https://github.com/stoplightio/studio-internal/issues/1632
> fix: handle invalid oauth2 security flows

- package.json
- src/oas3/transformers/content.ts
- yarn.lock
This package will be maintained and death to forks. Please merge whenever you're ready.
> chore: remove OAS to JSON Schema fork

- .github/CODEOWNERS
https://trello.com/c/br9qfXIG/115-add-code-owners-to-http-spec
> chore: add @marbemac as a codeowner

- src/oas3/guards.ts
- src/oas3/operation.ts
- src/oas3/transformers/__tests__/responses.test.ts
- src/oas3/transformers/responses.ts
- src/utils.ts
Fixes https://github.com/stoplightio/studio-internal/issues/1618
> fix: ignore nullish oas3 responses

- src/oas3/guards.ts
- src/oas3/transformers/__tests__/__snapshots__/responses.test.ts.snap
- src/oas3/transformers/__tests__/content.test.ts
- src/oas3/transformers/__tests__/responses.test.ts
- src/oas3/transformers/content.ts
- src/oas3/transformers/request.ts
- src/oas3/transformers/responses.ts
Fixes https://github.com/stoplightio/studio-internal/issues/1612
> fix: ignore nullish media objects

- src/oas2/transformers/__tests__/params.test.ts
- src/oas2/transformers/params.ts
Transforms oas2 parameter x-deprecated property.
> feat: support oas2 parameter x-deprecated

- src/__tests__/utils.test.ts
- src/utils.ts
Fixes https://github.com/stoplightio/platform-internal/issues/3589 + one potential issue with circular refs.
> fix: more bulletproof maybeResolveLocalRef

- README.md
Description of the approach to merging IHttpOperations.
> docs: merging strategy description

- src/oas/__tests__/__snapshots__/operation.test.ts.snap
- src/oas3/accessors.ts
- src/oas3/transformers/__tests__/securities.test.ts
I misunderstood the signature of `pickBy`, writing incorrect data. 🤦
> fix: correctly iterate on the key

- package.json
- yarn.lock
Incorporates https://github.com/openapi-contrib/openapi-schema-to-json-schema/pull/14
> chore(deps): @openapi-contrib/openapi-schema-to-json-schema to ^3.0.4

- src/oas/__tests__/__snapshots__/operation.test.ts.snap
- src/oas3/transformers/__tests__/responses.test.ts
- src/oas3/transformers/responses.ts
Needed for https://github.com/stoplightio/platform-internal/issues/5218
> fix(oas3): resolve $refs in media contents

- .github/CODEOWNERS
- package.json
- src/__tests__/utils.test.ts
- src/utils.ts
- yarn.lock
> fix: maybeResolveLocalRef keeps broken and follows $refs 

- package.json
- src/oas/__tests__/__snapshots__/operation.test.ts.snap
- src/oas3/index.ts
- src/oas3/transformers/content.ts
- src/oas3/transformers/schema.ts
- yarn.lock
Needed for stoplightio/platform-internal#5359
The code I left is what we actually use from that library, with a few changes.
> feat(deps): drop @openapi-contrib/openapi-schema-to-json-schema

- src/oas/transformers/schema/__tests__/schema.spec.ts
- src/oas/transformers/schema/index.ts
- src/oas2/operation.ts
- src/oas2/transformers/__tests__/params.test.ts
- src/oas2/transformers/__tests__/request.test.ts
- src/oas2/transformers/params.ts
- src/oas2/transformers/request.ts
- src/oas2/transformers/responses.ts
- src/oas3/__tests__/operation.test.ts
- src/oas3/transformers/content.ts
- src/oas3/transformers/request.ts
- src/postman/transformers/params.ts
For https://github.com/stoplightio/platform-internal/issues/5792
I'm going to easy this converter in Spectral.
> feat: support jsonSchemaDialect

- package.json
- src/postman/transformers/__tests__/params.test.ts
- src/postman/transformers/__tests__/response.test.ts
- src/postman/transformers/params.ts
- yarn.lock
[#11028](https://github.com/stoplightio/platform-internal/issues/11028)
updates to use our fork of json-schema-generator which has the optimist dep removed from it. Had to remove the optimist dependency because it uses an old version of `minimist` which has a critical security vulnerability.
> fix: remove optimist dep

- src/oas/__tests__/__snapshots__/operation.test.ts.snap
- src/oas3/__fixtures__/output.ts
- src/oas3/transformers/__tests__/__snapshots__/request.test.ts.snap
- src/oas3/transformers/request.ts
> fix(oas3): default to form for cookie and query params

- src/oas/transformers/schema/__tests__/schema.spec.ts
- src/oas/transformers/schema/index.ts
Fixes https://github.com/stoplightio/platform-internal/issues/11867
> chore(oas): make convertSchema accept any schema

- src/oas/resolver.ts
Already tested it in platform-internal
> fix(oas): avoid proxies

- src/oas/resolver.ts
- src/oas/transformers/components.ts
- src/oas/transformers/schema/index.ts
- src/oas2/transformers/params.ts
- src/oas2/transformers/request.ts
- src/oas3/__tests__/bundle.test.ts
- src/oas3/transformers/parameters.ts
- src/oas3/transformers/request.ts
- src/types.ts
Needs https://github.com/stoplightio/http-spec/pull/195
Fixes https://github.com/stoplightio/platform-internal/issues/11860
> fix(oas): tweak $ref resolving

- src/hash.ts
- src/oas/__tests__/__snapshots__/operation.test.ts.snap
- src/oas/__tests__/__snapshots__/service.test.ts.snap
- src/oas/__tests__/accessors.test.ts
- src/oas/__tests__/operation.test.ts
- src/oas/__tests__/service.test.ts
- src/oas/__tests__/tags.test.ts
- src/oas2/__tests__/__fixtures__/id/bundled.ts
- src/oas2/__tests__/accessors.test.ts
- src/oas2/__tests__/bundle.test.ts
- src/oas2/__tests__/operation.test.ts
- src/oas2/__tests__/service.test.ts
- src/oas3/__tests__/__fixtures__/id/bundled.ts
- src/oas3/__tests__/__fixtures__/id/legacy.ts
- src/oas3/__tests__/__fixtures__/shared-components/bundled.ts
- src/oas3/__tests__/__fixtures__/shared-components/legacy.ts
- src/oas3/__tests__/accessors.test.ts
- src/oas3/__tests__/bundle.test.ts
- src/oas3/__tests__/ids.test.ts
- src/oas3/__tests__/operation.test.ts
- src/oas3/__tests__/service.test.ts
- src/types.ts
No runtime changes besides the new option to run hasher without hashing, just test fixtures.
> chore: use unhashed ids in tests to make debugging easier

- src/oas/accessors.ts
- src/oas3/__tests__/__fixtures__/id/bundled.ts
- src/oas3/__tests__/__fixtures__/id/legacy.ts
- src/oas3/transformers/__tests__/request.test.ts
- src/oas3/transformers/request.ts
https://github.com/stoplightio/platform-internal/issues/15604
fixes the generation of path-defined parameters as new "instances" on the operation level. there currently is no place to attach path-defined parameters other than to the service (components) or operation (operation-defined).
* adjusted unit tests
> feat(oas3): path-defined params uniq per operation

- package.json
- yarn.lock
1.0.2 doesn't depend on request anymore.
#191
> Bump json-schema-generator

- src/generators.ts
[#15985](https://github.com/stoplightio/platform-internal/issues/15985)
- add unknown componentType to http_header id generator for stoplight-doc's usage
> fix: add unknown componentType for stoplight doc usage

- src/generators.ts
restores the unknown componenttype
> fix: restore missing header component type

- src/oas/transformers/schema/__tests__/schema.spec.ts
- src/oas/transformers/schema/keywords/format.ts
This fixes https://github.com/stoplightio/platform-internal/issues/15951.
I integrated the change with platform-internal using `yalc` and my local copy of the problematic project from issue https://github.com/stoplightio/platform-internal/issues/15951 publishes every time without problem now.
I also added a unit test to reproduce the bug, using a schema based on what I think was the problematic part of the original customer schema:
The fixed code passes the unit test.
> fix: don't set readonly property "explicitProperties"

- src/oas/__tests__/__snapshots__/operation.test.ts.snap
- src/oas/transformers/schema/keywords/format.ts
- src/oas3/__tests__/__fixtures__/id/bundled.ts
- src/oas3/__tests__/__fixtures__/id/legacy.ts
- src/oas3/__tests__/__fixtures__/shared-components/bundled.ts
- src/oas3/__tests__/__fixtures__/shared-components/legacy.ts
- src/oas3/__tests__/bundle.test.ts
- src/oas3/__tests__/operation.test.ts
- src/oas3/transformers/__tests__/__snapshots__/request.test.ts.snap
- src/oas3/transformers/request.ts
- src/utils.ts
additional metadata needed for oas3 - automerge is on!
> feat(oas3): expose explicit props and allow props in params

- src/oas/transformers/schema/index.ts
- src/oas2/__tests__/__fixtures__/id/bundled.ts
- src/oas2/__tests__/__fixtures__/id/input.json
- src/oas3/__tests__/__fixtures__/shared-components/bundled.ts
- src/oas3/__tests__/__fixtures__/shared-components/input.json
Needed for https://github.com/stoplightio/platform-internal/issues/16710
> fix(oas): preserve stable id on shared schema objects

- src/oas/__tests__/operation.test.ts
- src/oas/operation.ts
- src/oas/transformers/schema/index.ts
- src/utils.ts
https://github.com/stoplightio/platform-internal/issues/16924
used existing function to extract stable id if it exists for operations and callbacks. 
callbacks are not supported in the UI but would have the same issue as operations on path rename. 
Added automation test
> fix(oas): preserve stable id on operations

- package.json
- src/oas/__tests__/__snapshots__/service.test.ts.snap
- src/oas/externalDocs.ts
- src/oas/operation.ts
- src/oas/service.ts
- src/oas/tags.ts
- yarn.lock
[platform-internal #15432](https://app.zenhub.com/workspaces/-team-tacocat-5eb9bc4a1fddfe30b94f78b1/issues/gh/stoplightio/platform-internal/15432)
Add `externalDocs` to services, operations, and tag definitions.
- some unit tests added
- some integration tests fixed
> fix: 15432 add externalDocs

- package.json
- src/oas2/__tests__/__fixtures__/id/bundled.ts
- src/oas2/__tests__/bundle.test.ts
- src/oas2/service.ts
- src/oas3/__tests__/__fixtures__/examples/bundled.ts
- src/oas3/__tests__/__fixtures__/id/bundled.ts
- src/oas3/__tests__/__fixtures__/shared-components/bundled.ts
- src/oas3/__tests__/__snapshots__/operation.test.ts.snap
- src/oas3/__tests__/bundle.test.ts
- src/oas3/service.ts
- src/oas3/transformers/__tests__/callbacks.test.ts
- src/oas3/transformers/callbacks.ts
- yarn.lock
[#17287](https://github.com/stoplightio/platform-internal/issues/17287)
- add callbacks to components
- handles when a callback is a ref
- unit tests
- yalc'd into platform-internal
> feat(oas): handle callback refs and add callbacks to components

- src/oas2/__tests__/__fixtures__/id/bundled.ts
- src/oas2/__tests__/bundle.test.ts
- src/oas2/service.ts
- src/oas2/transformers/responses.ts
[#17287](https://github.com/stoplightio/platform-internal/issues/17287)
- maintains contents for shared oas2 responses
- unit tests
- yalc'd into platform-internal
> fix(oas): maintain contents in oas2 shared responses

- src/oas/__tests__/externalDocs.test.ts
- src/oas/externalDocs.ts
[#17480](https://github.com/stoplightio/platform-internal/issues/17480)
- do not include the description prop if it is undefined
- added unit tests
- yalc'd into platform-internal and those round trip tests pass
> fix(oas): exclude description prop if undefined

- src/oas2/__tests__/bundle.test.ts
- src/oas2/transformers/responses.ts
- src/oas3/__tests__/bundle.test.ts
[#17558](https://github.com/stoplightio/platform-internal/issues/17558)
- do not drop responses if they have external refs
- unit test
- yalc'd into platform-internal and refs.spec.ts tests pass
> fix(oas): do not drop responses if they have external ref oas2

- src/oas3/__tests__/bundle.test.ts
- src/oas3/transformers/examples.ts
> fix(oas): retain unresolved example refs

- src/oas3/__tests__/bundle.test.ts
- src/oas3/transformers/request.ts
https://github.com/stoplightio/platform-internal/issues/17558
like https://github.com/stoplightio/http-spec/pull/246, but for `requestBody`
unit test added
> fix(oas): retain unresolved request body refs

- src/oas3/__tests__/bundle.test.ts
- src/oas3/transformers/headers.ts
https://github.com/stoplightio/platform-internal/issues/17558
like #246 and #248, but for response headers
unit test added
> fix(oas): retain response header references

- src/oas/__tests__/__snapshots__/service.test.ts.snap
- src/oas/__tests__/fixtures/oas2-kitchen-sink.json
- src/oas/__tests__/fixtures/oas3-kitchen-sink.json
- src/oas/service.ts
- src/oas2/__tests__/__fixtures__/id/bundled.ts
- src/oas2/__tests__/bundle.test.ts
- src/oas2/__tests__/service.test.ts
- src/oas3/__tests__/__fixtures__/examples/bundled.ts
- src/oas3/__tests__/__fixtures__/examples/legacy.ts
- src/oas3/__tests__/__fixtures__/id/bundled.ts
- src/oas3/__tests__/__fixtures__/id/legacy.ts
- src/oas3/__tests__/__fixtures__/shared-components/bundled.ts
- src/oas3/__tests__/__fixtures__/shared-components/legacy.ts
- src/oas3/__tests__/bundle.test.ts
- src/oas3/__tests__/service.test.ts
- yarn.lock
collects extensions in the `info` section as `infoExtensions`
> feat(oas): support info extensions

- package.json
- src/oas2/__tests__/bundle.test.ts
- src/oas2/__tests__/service.test.ts
- src/oas2/service.ts
- src/oas3/__tests__/bundle.test.ts
- src/oas3/__tests__/service.test.ts
- src/oas3/service.ts
- yarn.lock
BREAKING CHANGE: IHttpService['security'] is a 2D array now
> feat(oas): support new IHttpService security

- package.json
- yarn.lock
Bumps `postman-collection` to address `semver` security issue
> fix(deps): bump postman-collection
